//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgc.Business.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sms.magfa.com/services/urn:SOAPSmsQueue")]
        public string pgc_Business_Magfa_SoapSmsQueuableImplementationService {
            get {
                return ((string)(this["pgc_Business_Magfa_SoapSmsQueuableImplementationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sep.shaparak.ir/payments/referencepayment.asmx")]
        public string pgc_Business_ir_shaparak_sep_PaymentIFBinding {
            get {
                return ((string)(this["pgc_Business_ir_shaparak_sep_PaymentIFBinding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.payamak-panel.com/post/Send.asmx")]
        public string pgc_Business_com_ppanel_api_Send {
            get {
                return ((string)(this["pgc_Business_com_ppanel_api_Send"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.payamak-panel.com/post/Send.asmx")]
        public string pgc_Business_com_ppanel_api_Send1 {
            get {
                return ((string)(this["pgc_Business_com_ppanel_api_Send1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sep.shaparak.ir/payments/referencepayment.asmx")]
        public string pgc_Business_ir_shaparak_sep_PaymentIFBinding1 {
            get {
                return ((string)(this["pgc_Business_ir_shaparak_sep_PaymentIFBinding1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sms.magfa.com/services/urn:SOAPSmsQueue")]
        public string pgc_Business_Magfa_SoapSmsQueuableImplementationService1 {
            get {
                return ((string)(this["pgc_Business_Magfa_SoapSmsQueuableImplementationService1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bpm.shaparak.ir/pgwchannel/services/pgw")]
        public string pgc_Business_ir_shaparak_bpm_PaymentGatewayImplService {
            get {
                return ((string)(this["pgc_Business_ir_shaparak_bpm_PaymentGatewayImplService"]));
            }
        }
    }
}
