namespace pgc.Model.Enums
{
    public enum UserMessageKey
    {
        Succeed,
        ErrorSample,
        WarningSample,
        InfoSample,
        Failed,
        NoItemSelectedForBulkOperation,
        InvalidUsernameOrPassword,
        InvalidEmailOrPassword,
        DisableLoginByUserName,
        LoginByEmail,
        InactiveUser,
        ContactAdminInErrorPersistance,
        SessionExpired,
        AccessDenied,
        UserAlreadyLoggedIn,
        UserAlreadyLoggedOut,
        DuplicateUsername,
        DuplicateEmail,
        PasswordMinLengthExceed,
        RegisterGreeting,
        ThankUserForComment,
        ValidateUrlKey,
        DuplicateUrlKey,
        ThankBranchRequest,
        DuplicateIPAddress,
        InvalidOldPassword,
        InvalidEndDemandDate,
        UnselectedBranch,
        InvalidQuantity,
        NoItemSelectedForOrder,
        DuplicateLotteryCode,
        ThankForParticipateLottery,
        InvalidExpireDate,
        NewsShowAfterConfirm,
        AlreadyRegistered,

        //OnlineOrder Allow
        OnlineOrderIsSuspended,
        OnlineOrderSuspendByAdmin,

        #region Event,Sms,Mail,OnlinePayments

        //Keys For SMS Sending
        MismatchMessageBodyAndType,
        MismatchMessageBodyAndSMSCount,
        NoMessageBody,
        NoRecipientNumber,
        CountMismatchForRecipientsAndMessage,
        InvalidRecipientNumber,
        ErrorOccuredInSend,
        UnknownOccuredInSend,
        NoPrivateNo,

        //New Keys For .Events .OnlinePayment .SMSAttempt .EmailAttemp .SentEmail

        NoUserSelected,
        UserNoEmail,
        UserNoMobile,
        NotValidEmail,
        NotValidMobile,
        DuplicateUserForEvent,
        DuplicateManualEmailEvent,
        DuplicateManualMobileEvent,

        //Email Messages
        InvalidSenderEmail,
        InvalidRecipientEmail,
        FileExtensionIsBlocked,
        IncompatibleFile,
        NoEmailBody,
        NoEmailSubject,
        SMTPError,
        DupliacteEmailAddress,
        SMTPParametersNotInitiate,
        NoEmailSent,
        BlockingFailed,
        InvalidAllRecipientEmails,
        DBInsertingProblem,
        AllEmailSent,
        SomeEmailSent,
        InvalidRecieverEmail,
        SomeSystemEventsBindThis,
        SomeScheduleEventsBindThis,
        NotRetrieveScheduleEvent,
        EmailSendingFailed,
        SMSSendingFailed,
        NoRecipientEmail,
        FileTooLarge,
        PreventDeleteMailBodyCauseHaveMailAction,
        PreventDeleteMessageBodyCauseHaveSMSAction,
        PreventSaveCauseHaveSMSAdminAction,
        PreventSaveCauseHaveEmailUserAction,
        PreventSaveCauseHaveSMSUserAction,
        PreventSaveCauseHaveEmailAdminAction,

        //Online Saman
        Canceled_By_User,
        Invalid_Amount,
        Invalid_Transaction,
        Invalid_Card_Number,
        No_Such_Issuer,
        Expired_Card_Pick_Up,
        Allowable_PIN_Tries_Exceeded_Pick_Up,
        Incorrect_PIN,
        Exceeds_Withdrawal_Amount_Limit,
        Transaction_Cannot_Be_Completed,
        Response_Received_Too_Late,
        Suspected_Fraud_Pick_Up,
        No_Sufficient_Funds,
        Issuer_Down_Slm,
        TME_Error,
        OK,
        PreventSaveCauseAccessNotSelect,
        PreventSaveCauseRoleNotSelect,
        PreventSaveCauseUserNotSelect,

        //VerifyResult
        Err_0,
        Err_1,
        Err_2,
        Err_3,
        Err_4,
        Err_5,
        Err_6,
        Err_7,
        Err_8,
        Err_9,
        Err_10,
        Err_11,
        Err_12,
        Err_13,
        Err_14,
        Err_15,
        Err_16,
        Err_17,
        Err_18,
        Err_20,

        //Online Messages
        DoubleSpending,
        FailedOnlineTransaction,
        NeedToReverse,
        NeedToReverseSome,
        ReverseCompleted,
        OnlineResNumIsEmpty,
        OnlineRefNumIsEmpty,
        OnlineTransactionStateIsEmpty,
        OnlineVerificationCompleted,
        OnlinePaymentSucceedText,
        PreventDeleteOrderForOnlinePayment,

        //Correction Cascading Delete
        FirstDeleteGalleryPic,
        FirstDeletePollChoisesANDResults,
        JustDeactiveLottery,
        FirstDeletOrMoveSitemapItems,
        FirstDeletCities,
        UsersUseCitySoCantDelete,
        UserHasOnlineTransactionOnlyCanDeactive,
        FirstDeleteOrMoveBranchPic,
        FirstDeleteOrMoveUsers,
        FirstDeleteBranchDemands,
        FirstMoveOrDeleteUsersForAccessLevel,
        PrivateNoHasRecievSMSSoDeactive,
        PrivateNoHasSentSMSSoDeactive,
        SomeSystemEventActionDisabledForThisPrivateNo,



        #endregion


        //Finance Cycle
        InvalidTransaction,// Manual Charge


        InvalidOnlineID,
        PleaseNotifyAdminForInsertOnlineTransaction,
        PleaseNotifyCenterForInsertOnlineTransaction,
        DuplicateBankAccount,
        PreventDeleteBankAccountCauseCascading,
        PleaseSelectBankAccount,
        BranchOfflineInsertSucceed,
        SucceedAndInsertTransaction,
        PreventDeletBranchPaymentCauseHasTransaction,
        BranchOrderNew_DeliverTimeConstraint,
        BranchOrderNewInsufficientCredit,
        BranchOrderNew_InvalidTimeForAccept,
        BranchOrderNew_NoTitleSelected,
        BranchOrderNew_NoQuantitySelected,
        InvalidBranchOrderID,
        BranchTransactionDeleteFailed,
        BranchOrderAdminConfirmed,
        BranchOrderAdminRejected,
        BranchOrderAdminCorrection,
        BranchOrderPreventDeleteCauseHaveTransaction,
        BranchOrderNew_SucceedByBranch,
        BranchOrderDeleteSucceed,
        BranchOrder_InvalidTimeForAccept,
        BranchOrder_SucceedByBranch,
        BranchOrder_DeliverTimeConstraint,
        BranchReturnOrderAdminConfirmed,
        BranchReturnOrderAdminRejected,
        BranchReturnOrderAdminCorrection,
        BranchReturnOrder_SucceedByBranch,
        BranchReturnOrderNew_SucceedByBranch,
        BranchReturnOrderPreventDeleteCauseHaveTransaction,
        BranchReturnOrderNew_NoQuantitySelected,
        BranchReturnOrderNew_NoTitleSelected,
        BranchReturnOrder_ReturnQuantityIsMoreThanMax,
        BranchReturnOrder_ConstraintStatusOfBranchOrder,
        BranchOrderLogInsertingFailed,
        BranchOrderTitlePreventDeleteCauseHasDetails,


        ChartHasNoData,
        BranchIsAlreadyActive,
        BranchIsAlreadyDeActive,
        BranchCreditIsNotBalanced,
        Branch_ActivationIsComplete,
        Branch_DeActivationIsComplete,
        BranchDeletePreventCauseHasTransactions,


        BranchOrderTitleGroupPreventDeleteCauseHasOrderTitle,
        BranchOrderManagement_InvalidQuantity,
        BranchOrderManagement_SelectedHasNoNumber,
        PreventDeleteBranchOrderShipmentStateCauseHaveOrders,
        BranchOrderNew_InsufficientQuantitySelected,
        BranchOrderNew_DontAllowAnyOrderTitle,
        BranchReturnOrder_SucceedEditByAdmin,
        BranchOrder_SucceedEditByAdmin,
        BranchReturnOrder_AdminFinalized,
        BranchLackOrder_AdminConfirmed,
        BranchLackOrder_AdminCanceled,
        BranchLackOrder_SucceedEditByAdmin,
        BranchLackOrder_SucceedByBranch,
        BranchLackOrderNew_SucceedByBranch,
        BranchLackOrderNew_DontCreateCauseDontHaveTodayOrder,
        BranchLackOrderNew_NoTitleSelected,
        BranchLackOrderNew_NoQuantitySelected,
        BranchLackOrder_ConstraintStatusOfBranchOrder,
        BranchReturnOrder_PreventAdminFinalizedCauseNotConfirmed,
        BranchReturnOrder_PreventAdminEditCauseNotPending,
        BranchOrder_PreventAdminFinalizedCauseNotConfirmed,
        BranchOrder_PreventAdminEditCauseNotPending,
        BranchOrder_AdminFinalized,
        BranchReturnOrderAdminRollingBackFinalized,
        BranchReturnOrderAdminDelete,
        BranchOrderAdminRollingBackFinalized,
        BranchOrderAdminDelete,
        BranchLackOrderAdminRollingBackFinalized,
        BranchLackOrderAdminDelete,
        BranchOrderTitle_DuplicateTitle,
        BranchOrderTitleGroup_DuplicateTitle,
        BranchLackOrderNew_MoreThaNOrdered,
        BranchOrderAdminEdit_InsufficientQuantitySelected,
        BranchLackOrderNew_DontCreateCauseOrderIsFinalized,

        PaidOrderMustHaveBranch,
        CorrespondingTransactionUpdated,

        //payamak panel sendSms() return values
        PayamakPanel_InavalidUsernameOrPassword,
        PayamakPanel_InsufficientCredit,
        PayamakPanel_LimitationOnDailySend,
        PayamakPanel_LimitationOnSendVolume,
        PayamakPanel_InvalidSenderNumber,
        PayamakPanel_UpdatingPPServer,
        PayamakPanel_TextIncludedFilteredWord,
        PayamakPanel_ImpossibleByPublicNumber,
        PayamakPanel_DisableUser,
        PayamakPanel_DidNotSent,
        PayamakPanel_DocumentsInComplete,

        //order
        ThankForOrder,


        EmailAndPassConfirmation,
        LoginOnlyByEmail,
        NoRefNum,
        OnlinePaymentIsSuccessful,
        PaymentStatusChangedToNotPaid,
        BankWebServiceNoResponse
    }
}