//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public Advertisement()
        {
            this.PanelPages = new HashSet<PanelPage>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public int AdvType { get; set; }
        public string FileAddress { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string NavigateUrl { get; set; }
        public string AltText { get; set; }
        public string Html { get; set; }
        public string RegPersianDate { get; set; }
        public string ExpirePersianDate { get; set; }
        public int DispOrder { get; set; }
        public int MarginTop { get; set; }
        public int MarginRight { get; set; }
        public int MarginBottom { get; set; }
        public int MarginLeft { get; set; }
    
        public virtual ICollection<PanelPage> PanelPages { get; set; }
    }
}
