//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndroidSetting
    {
        public long ID { get; set; }
        public string NavHeaderImage { get; set; }
        public int NewsCount { get; set; }
        public string QualityCharter { get; set; }
    }
}
