//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchOrderTitle
    {
        public BranchOrderTitle()
        {
            this.Branch_BranchOrderTitle = new HashSet<Branch_BranchOrderTitle>();
            this.BranchLackOrderDetails = new HashSet<BranchLackOrderDetail>();
            this.BranchOrderDetails = new HashSet<BranchOrderDetail>();
            this.BranchReturnOrderDetails = new HashSet<BranchReturnOrderDetail>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public long Price { get; set; }
        public long BranchOrderTitleGroup_ID { get; set; }
        public int DisplayOrder { get; set; }
        public string ImagePath { get; set; }
        public bool IsOrderForAllBranch { get; set; }
    
        public virtual ICollection<Branch_BranchOrderTitle> Branch_BranchOrderTitle { get; set; }
        public virtual ICollection<BranchLackOrderDetail> BranchLackOrderDetails { get; set; }
        public virtual ICollection<BranchOrderDetail> BranchOrderDetails { get; set; }
        public virtual BranchOrderTitleGroup BranchOrderTitleGroup { get; set; }
        public virtual ICollection<BranchReturnOrderDetail> BranchReturnOrderDetails { get; set; }
    }
}
