//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchPic
    {
        public long ID { get; set; }
        public long Branch_ID { get; set; }
        public string ImagePath { get; set; }
        public string ThumbPath { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
