//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchFinanceLog
    {
        public long ID { get; set; }
        public int ActionType { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public string Description { get; set; }
        public long Branch_ID { get; set; }
        public string BranchTitle { get; set; }
        public int LogType { get; set; }
        public long LogType_ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
