//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Branch_BranchOrderTitle = new HashSet<Branch_BranchOrderTitle>();
            this.BranchContacts = new HashSet<BranchContact>();
            this.BranchOrders = new HashSet<BranchOrder>();
            this.BranchFinanceLogs = new HashSet<BranchFinanceLog>();
            this.BranchPics = new HashSet<BranchPic>();
            this.BranchReturnOrders = new HashSet<BranchReturnOrder>();
            this.BranchPayments = new HashSet<BranchPayment>();
            this.BranchTransactions = new HashSet<BranchTransaction>();
            this.Users = new HashSet<User>();
            this.UserComments = new HashSet<UserComment>();
            this.Orders = new HashSet<Order>();
            this.Circulars = new HashSet<Circular>();
            this.Comments = new HashSet<Comment>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string BranchInfo { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string HoursServingFood { get; set; }
        public string HoursOrdering { get; set; }
        public int NumberOfChair { get; set; }
        public string TransportCost { get; set; }
        public string LargeThumbImagePath { get; set; }
        public string UrlKey { get; set; }
        public string Description { get; set; }
        public string LargeImagePath { get; set; }
        public string ThumbListPath { get; set; }
        public string Body { get; set; }
        public int DispOrder { get; set; }
        public bool AllowOnlineOrder { get; set; }
        public string AllowOnlineOrderTimeFrom { get; set; }
        public string AllowOnlineOrderTimeTo { get; set; }
        public long MinimumCredit { get; set; }
        public bool IsActive { get; set; }
        public int BranchType { get; set; }
        public double Longitude { get; set; }
        public double latitude { get; set; }
    
        public virtual ICollection<Branch_BranchOrderTitle> Branch_BranchOrderTitle { get; set; }
        public virtual ICollection<BranchContact> BranchContacts { get; set; }
        public virtual ICollection<BranchOrder> BranchOrders { get; set; }
        public virtual ICollection<BranchFinanceLog> BranchFinanceLogs { get; set; }
        public virtual ICollection<BranchPic> BranchPics { get; set; }
        public virtual ICollection<BranchReturnOrder> BranchReturnOrders { get; set; }
        public virtual ICollection<BranchPayment> BranchPayments { get; set; }
        public virtual ICollection<BranchTransaction> BranchTransactions { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Circular> Circulars { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
