//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchContact
    {
        public long ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public long Branch_ID { get; set; }
        public string BranchTitle { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
