//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchLackOrderDetail
    {
        public long ID { get; set; }
        public long SinglePrice { get; set; }
        public long Quantity { get; set; }
        public long TotalPrice { get; set; }
        public string BranchOrderTitle_Title { get; set; }
        public Nullable<long> BranchOrderTitle_ID { get; set; }
        public long BranchLackOrder_ID { get; set; }
    
        public virtual BranchLackOrder BranchLackOrder { get; set; }
        public virtual BranchOrderTitle BranchOrderTitle { get; set; }
    }
}
