//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchRequest
    {
        public long ID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string FullName { get; set; }
        public string ApplicatorName { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string BranchLocation { get; set; }
        public int LocationType { get; set; }
        public bool HaveBackgroung { get; set; }
        public int Status { get; set; }
        public System.DateTime BRDate { get; set; }
        public string BRPersianDate { get; set; }
        public string Description { get; set; }
    }
}
