//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyBasket
    {
        public long ID { get; set; }
        public long User_ID { get; set; }
        public long Product_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
