//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circular
    {
        public Circular()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public string PersiabDate { get; set; }
        public bool IsVisible { get; set; }
        public bool IsActiveForUser { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
