//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Users = new HashSet<User>();
        }
    
        public long ID { get; set; }
        public long Province_ID { get; set; }
        public string Title { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
