//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long ID { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public bool IsDisplay { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public long Like { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
    }
}
