//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendAttempt
    {
        public EmailSendAttempt()
        {
            this.SentEmailBlocks = new HashSet<SentEmailBlock>();
        }
    
        public long ID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Recipients { get; set; }
        public int EventType { get; set; }
        public Nullable<long> OccuredEvent_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public string FilePath1 { get; set; }
        public string FilePath2 { get; set; }
        public string FilePath3 { get; set; }
        public string FilePath4 { get; set; }
        public string FilePath5 { get; set; }
        public string FilePath6 { get; set; }
        public string FilePath7 { get; set; }
        public string FilePath8 { get; set; }
        public string FilePath9 { get; set; }
        public string FilePath10 { get; set; }
        public int SentEmail_Count { get; set; }
        public int FailedEmail_Count { get; set; }
        public int TotalEmail_Count { get; set; }
        public int SentBlock_Count { get; set; }
        public int FailedBlock_Count { get; set; }
        public int TotalBlock_Count { get; set; }
        public int BlockSize { get; set; }
        public int InvalidEmailAddress_Count { get; set; }
    
        public virtual ICollection<SentEmailBlock> SentEmailBlocks { get; set; }
    }
}
