//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionType { get; set; }
        public string InnerException { get; set; }
        public string StackTrace { get; set; }
        public Nullable<long> User_ID { get; set; }
    }
}
