//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryPic
    {
        public long ID { get; set; }
        public long Gallery_ID { get; set; }
        public string Description { get; set; }
        public int DispOrder { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
