//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lottery
    {
        public Lottery()
        {
            this.LotteryDetails = new HashSet<LotteryDetail>();
            this.LotteryWiners = new HashSet<LotteryWiner>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public System.DateTime RegDate { get; set; }
        public string RegPersianDate { get; set; }
    
        public virtual ICollection<LotteryDetail> LotteryDetails { get; set; }
        public virtual ICollection<LotteryWiner> LotteryWiners { get; set; }
    }
}
