//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public int DisplayOrder { get; set; }
        public string NavigationUrl { get; set; }
        public string HtmlCode { get; set; }
        public bool IsHtml { get; set; }
        public bool DispInHome { get; set; }
        public bool DispInOtherPage { get; set; }
        public bool IsBlank { get; set; }
    }
}
