//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePayment
    {
        public long ID { get; set; }
        public long Order_ID { get; set; }
        public string ResNum { get; set; }
        public long Amount { get; set; }
        public string TransactionState { get; set; }
        public string RefNum { get; set; }
        public long ResultTransaction { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
