//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionLookupDetail
    {
        public long ID { get; set; }
        public long OptionLookup_ID { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
    
        public virtual OptionLookup OptionLookup { get; set; }
    }
}
