//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionCategory
    {
        public OptionCategory()
        {
            this.Options = new HashSet<Option>();
            this.OptionCategory1 = new HashSet<OptionCategory>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public Nullable<long> Parent_OptionCategory_ID { get; set; }
        public float DisplayOrder { get; set; }
        public bool GrantAdmin { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<OptionCategory> OptionCategory1 { get; set; }
        public virtual OptionCategory OptionCategory2 { get; set; }
    }
}
