//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionLookup
    {
        public OptionLookup()
        {
            this.Options = new HashSet<Option>();
            this.OptionLookupDetails = new HashSet<OptionLookupDetail>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual ICollection<OptionLookupDetail> OptionLookupDetails { get; set; }
    }
}
