//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long ID { get; set; }
        public long Order_ID { get; set; }
        public Nullable<long> Product_ID { get; set; }
        public int Quantity { get; set; }
        public long UnitPrice { get; set; }
        public long SumPrice { get; set; }
        public string ProductTitle { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
