//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OnlinePayments = new HashSet<OnlinePayment>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public long ID { get; set; }
        public long User_ID { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderPersianDate { get; set; }
        public long TotalAmount { get; set; }
        public long PayableAmount { get; set; }
        public int OrderStatus { get; set; }
        public int PaymentType { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Comment { get; set; }
        public bool IsPaid { get; set; }
        public string BranchTitle { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<OnlinePayment> OnlinePayments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
