//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelPage
    {
        public PanelPage()
        {
            this.PanelPage1 = new HashSet<PanelPage>();
            this.Advertisements = new HashSet<Advertisement>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Feature_ID { get; set; }
        public Nullable<long> Parent_Page_ID { get; set; }
        public string Title { get; set; }
        public string UITitle { get; set; }
        public string URL { get; set; }
        public int PageSize { get; set; }
        public float DisplayOrder { get; set; }
        public string RouteName { get; set; }
        public string RouteUrl { get; set; }
        public bool IsLookup { get; set; }
        public bool AdvSupport { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual ICollection<PanelPage> PanelPage1 { get; set; }
        public virtual PanelPage PanelPage2 { get; set; }
        public virtual ICollection<Advertisement> Advertisements { get; set; }
    }
}
