//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateNo
    {
        public PrivateNo()
        {
            this.ReceivedMessages = new HashSet<ReceivedMessage>();
            this.SentSMS = new HashSet<SentSMS>();
            this.SystemEventActions = new HashSet<SystemEventAction>();
        }
    
        public long ID { get; set; }
        public string Number { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<ReceivedMessage> ReceivedMessages { get; set; }
        public virtual ICollection<SentSMS> SentSMS { get; set; }
        public virtual ICollection<SystemEventAction> SystemEventActions { get; set; }
    }
}
