//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BuyBaskets = new HashSet<BuyBasket>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Materials = new HashSet<Material>();
            this.Comments = new HashSet<Comment>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string ProductPicPath { get; set; }
        public long Price { get; set; }
        public bool Accessories { get; set; }
        public bool AllowOnlineOrder { get; set; }
        public string SliderProductPicPath { get; set; }
        public string SliderHoverProductPicPath { get; set; }
        public bool DisplayInSlider { get; set; }
        public int DispOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<BuyBasket> BuyBaskets { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Material> Materials { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
