//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentSMS
    {
        public long ID { get; set; }
        public Nullable<long> GatewayMessageID { get; set; }
        public long PrivateNo_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public string RecipientNumber { get; set; }
        public int SendStatus { get; set; }
        public int PhoneDeliveryCount { get; set; }
        public int PhoneFailCount { get; set; }
        public int TeleDeliveryCount { get; set; }
        public int TeleFailCount { get; set; }
        public string Body { get; set; }
        public int MessageType { get; set; }
        public Nullable<int> FaultType { get; set; }
        public int SMSCount { get; set; }
        public long SMSSendAttempt_ID { get; set; }
    
        public virtual SMSSendAttempt SMSSendAttempt { get; set; }
        public virtual PrivateNo PrivateNo { get; set; }
    }
}
