//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideMenuCat
    {
        public SideMenuCat()
        {
            this.SideMenuItems = new HashSet<SideMenuItem>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public int DisplayOrder { get; set; }
        public string NavigationUrl { get; set; }
        public bool IsVisible { get; set; }
        public bool IsBlank { get; set; }
    
        public virtual ICollection<SideMenuItem> SideMenuItems { get; set; }
    }
}
