//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemEventAction
    {
        public long ID { get; set; }
        public long SystemEvent_ID { get; set; }
        public string ManualEmail { get; set; }
        public string ManualSMS { get; set; }
        public bool Custom_User_SMS { get; set; }
        public bool Custom_User_Email { get; set; }
        public Nullable<long> Custom_User_ID { get; set; }
        public Nullable<long> Custom_User_ID_SMS { get; set; }
        public bool Custom_Role_SMS { get; set; }
        public bool Custom_Role_Email { get; set; }
        public Nullable<int> Custom_Role_ID { get; set; }
        public Nullable<int> Custom_Role_ID_SMS { get; set; }
        public bool Custom_AccessLevel_SMS { get; set; }
        public bool Custom_AccessLevel_Email { get; set; }
        public Nullable<long> Custom_AccessLevel_ID { get; set; }
        public Nullable<long> Custom_AccessLevel_ID_SMS { get; set; }
        public bool Related_Guest_Email { get; set; }
        public bool Related_User_Email { get; set; }
        public bool Related_Branch_Email { get; set; }
        public bool Related_Doer_Email { get; set; }
        public bool Related_Guest_SMS { get; set; }
        public bool Related_User_SMS { get; set; }
        public bool Related_Branch_SMS { get; set; }
        public bool Related_Doer_SMS { get; set; }
        public Nullable<long> PrivateNo_ID { get; set; }
    
        public virtual PrivateNo PrivateNo { get; set; }
        public virtual SystemEvent SystemEvent { get; set; }
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual User User { get; set; }
    }
}
