//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemEvent
    {
        public SystemEvent()
        {
            this.SystemEventVariables = new HashSet<SystemEventVariable>();
            this.OccuredSystemEvents = new HashSet<OccuredSystemEvent>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string EventKey { get; set; }
        public bool Support_Manual_Email { get; set; }
        public bool Support_Manual_SMS { get; set; }
        public bool Support_Custom_User_SMS { get; set; }
        public bool Support_Custom_User_Email { get; set; }
        public bool Support_Custom_Role_SMS { get; set; }
        public bool Support_Custom_Role_Email { get; set; }
        public bool Support_Custom_AccessLevel_SMS { get; set; }
        public bool Support_Custom_AccessLevel_Email { get; set; }
        public bool Support_Related_Guest_Email { get; set; }
        public bool Support_Related_User_Email { get; set; }
        public bool Support_Related_Branch_Email { get; set; }
        public bool Support_Related_Doer_Email { get; set; }
        public bool Support_Related_Guest_SMS { get; set; }
        public bool Support_Related_User_SMS { get; set; }
        public bool Support_Related_Branch_SMS { get; set; }
        public bool Support_Related_Doer_SMS { get; set; }
        public string Template_Admin_Email { get; set; }
        public string Template_Admin_SMS { get; set; }
        public string Template_User_Email { get; set; }
        public string Template_User_SMS { get; set; }
    
        public virtual ICollection<SystemEventVariable> SystemEventVariables { get; set; }
        public virtual SystemEventAction SystemEventAction { get; set; }
        public virtual ICollection<OccuredSystemEvent> OccuredSystemEvents { get; set; }
    }
}
