//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemEventVariable
    {
        public long ID { get; set; }
        public long SystemEvent_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Alias { get; set; }
    
        public virtual SystemEvent SystemEvent { get; set; }
    }
}
