//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BranchFinanceLogs = new HashSet<BranchFinanceLog>();
            this.BuyBaskets = new HashSet<BuyBasket>();
            this.Orders = new HashSet<Order>();
            this.SystemEventActions = new HashSet<SystemEventAction>();
        }
    
        public long ID { get; set; }
        public Nullable<long> City_ID { get; set; }
        public string FullName { get; set; }
        public Nullable<long> AccessLevel_ID { get; set; }
        public string Username { get; set; }
        public string pwd { get; set; }
        public int ActivityStatus { get; set; }
        public string NationalCode { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string SignUpPersianDate { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<long> Branch_ID { get; set; }
    
        public virtual ICollection<BranchFinanceLog> BranchFinanceLogs { get; set; }
        public virtual ICollection<BuyBasket> BuyBaskets { get; set; }
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual City City { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<SystemEventAction> SystemEventActions { get; set; }
    }
}
