//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public long ID { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Topic { get; set; }
        public string Body { get; set; }
        public string UCPersianDate { get; set; }
        public System.DateTime UCDate { get; set; }
        public int Status { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public string BranchTitle { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
