//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public long ID { get; set; }
        public string Key { get; set; }
        public int Type { get; set; }
        public int Direction { get; set; }
        public int Behaviour { get; set; }
        public string Description { get; set; }
    }
}
