//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrd.Business.SamanBank {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Foo", ConfigurationName="SamanBank.PaymentIF")]
    public interface PaymentIF {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        mrd.Business.SamanBank.ReverseResult reverseTransResult(string String_1, string String_2, string String_3, double double_4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        int reverseTransaction(string String_1, string String_2, string String_3, double double_4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        double verifyTransaction(string String_1, string String_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string verifyTransaction2(string String_1, string String_2, string String_3, string String_4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string verifyTransaction3(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string verifyTransaction4(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6, string String_7, string String_8);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransBean))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        mrd.Business.SamanBank.TransResult viewTransaction(string String_1, string String_2, mrd.Business.SamanBank.FilterBean FilterBean_3);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Foo")]
    public partial class ReverseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string refNumField;
        
        private int resultCodeField;
        
        private string resultDescField;
        
        /// <remarks/>
        public string refNum {
            get {
                return this.refNumField;
            }
            set {
                this.refNumField = value;
                this.RaisePropertyChanged("refNum");
            }
        }
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        public string resultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
                this.RaisePropertyChanged("resultDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Foo")]
    public partial class TransBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountField;
        
        private short docTypeField;
        
        private short docstateField;
        
        private string localTransDateField;
        
        private string mtIdField;
        
        private string refNumField;
        
        private string resNumField;
        
        private string transDateField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        public short docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("docType");
            }
        }
        
        /// <remarks/>
        public short docstate {
            get {
                return this.docstateField;
            }
            set {
                this.docstateField = value;
                this.RaisePropertyChanged("docstate");
            }
        }
        
        /// <remarks/>
        public string localTransDate {
            get {
                return this.localTransDateField;
            }
            set {
                this.localTransDateField = value;
                this.RaisePropertyChanged("localTransDate");
            }
        }
        
        /// <remarks/>
        public string mtId {
            get {
                return this.mtIdField;
            }
            set {
                this.mtIdField = value;
                this.RaisePropertyChanged("mtId");
            }
        }
        
        /// <remarks/>
        public string refNum {
            get {
                return this.refNumField;
            }
            set {
                this.refNumField = value;
                this.RaisePropertyChanged("refNum");
            }
        }
        
        /// <remarks/>
        public string resNum {
            get {
                return this.resNumField;
            }
            set {
                this.resNumField = value;
                this.RaisePropertyChanged("resNum");
            }
        }
        
        /// <remarks/>
        public string transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
                this.RaisePropertyChanged("transDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Foo")]
    public partial class TransResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string resultDescField;
        
        private TransBean[] transBeanField;
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        public string resultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
                this.RaisePropertyChanged("resultDesc");
            }
        }
        
        /// <remarks/>
        public TransBean[] transBean {
            get {
                return this.transBeanField;
            }
            set {
                this.transBeanField = value;
                this.RaisePropertyChanged("transBean");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Foo")]
    public partial class FilterBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short docStateField;
        
        private short docTypeField;
        
        private double maxAmountField;
        
        private string maxTransDateField;
        
        private double minAmountField;
        
        private string minTransDateField;
        
        private string refNumField;
        
        private string resNumField;
        
        /// <remarks/>
        public short docState {
            get {
                return this.docStateField;
            }
            set {
                this.docStateField = value;
                this.RaisePropertyChanged("docState");
            }
        }
        
        /// <remarks/>
        public short docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("docType");
            }
        }
        
        /// <remarks/>
        public double maxAmount {
            get {
                return this.maxAmountField;
            }
            set {
                this.maxAmountField = value;
                this.RaisePropertyChanged("maxAmount");
            }
        }
        
        /// <remarks/>
        public string maxTransDate {
            get {
                return this.maxTransDateField;
            }
            set {
                this.maxTransDateField = value;
                this.RaisePropertyChanged("maxTransDate");
            }
        }
        
        /// <remarks/>
        public double minAmount {
            get {
                return this.minAmountField;
            }
            set {
                this.minAmountField = value;
                this.RaisePropertyChanged("minAmount");
            }
        }
        
        /// <remarks/>
        public string minTransDate {
            get {
                return this.minTransDateField;
            }
            set {
                this.minTransDateField = value;
                this.RaisePropertyChanged("minTransDate");
            }
        }
        
        /// <remarks/>
        public string refNum {
            get {
                return this.refNumField;
            }
            set {
                this.refNumField = value;
                this.RaisePropertyChanged("refNum");
            }
        }
        
        /// <remarks/>
        public string resNum {
            get {
                return this.resNumField;
            }
            set {
                this.resNumField = value;
                this.RaisePropertyChanged("resNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentIFChannel : mrd.Business.SamanBank.PaymentIF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentIFClient : System.ServiceModel.ClientBase<mrd.Business.SamanBank.PaymentIF>, mrd.Business.SamanBank.PaymentIF {
        
        public PaymentIFClient() {
        }
        
        public PaymentIFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentIFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentIFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentIFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public mrd.Business.SamanBank.ReverseResult reverseTransResult(string String_1, string String_2, string String_3, double double_4) {
            return base.Channel.reverseTransResult(String_1, String_2, String_3, double_4);
        }
        
        public int reverseTransaction(string String_1, string String_2, string String_3, double double_4) {
            return base.Channel.reverseTransaction(String_1, String_2, String_3, double_4);
        }
        
        public double verifyTransaction(string String_1, string String_2) {
            return base.Channel.verifyTransaction(String_1, String_2);
        }
        
        public string verifyTransaction2(string String_1, string String_2, string String_3, string String_4) {
            return base.Channel.verifyTransaction2(String_1, String_2, String_3, String_4);
        }
        
        public string verifyTransaction3(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6) {
            return base.Channel.verifyTransaction3(String_1, String_2, String_3, String_4, String_5, String_6);
        }
        
        public string verifyTransaction4(string String_1, string String_2, string String_3, string String_4, string String_5, string String_6, string String_7, string String_8) {
            return base.Channel.verifyTransaction4(String_1, String_2, String_3, String_4, String_5, String_6, String_7, String_8);
        }
        
        public mrd.Business.SamanBank.TransResult viewTransaction(string String_1, string String_2, mrd.Business.SamanBank.FilterBean FilterBean_3) {
            return base.Channel.viewTransaction(String_1, String_2, FilterBean_3);
        }
    }
}
